kafka-ui:
    ingress:
        enabled: true
        annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
        ingressClassName: "nginx"
        path: "/"
        pathType: "Prefix"  
        host: "kafka.kgmm.co.uk"
        tls:
            enabled: true
            secretName: "kafka_ui-tls-certificate"