kafka-ui:
    yamlApplicationConfig:
        kafka:
            clusters:
                - name: yaml
                  bootstrapServers: kafka.kafka:29092
    ingress:
        enabled: true
        annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
        ingressClassName: nginx
        path: "/"
        pathType: "Prefix"  
        host: kafka.kgmm.co.uk
        tls:
            enabled: true
            secretName: kafkaui-tls-certificate