n8n:
  persistence:
    enabled: true
    type: dynamic
    accessModes:
      - ReadWriteOnce
    size: 1Gi
  podSecurityContext:
    fsGroup: 1000
  securityContext:
    runAsUser: 1000

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: n8n.kgmm.co.uk
        paths:
          - /
    tls:
      - secretName: n8n-tls-certificate
        hosts:
          - n8n.kgmm.co.uk
    className: "nginx"